apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-03-19T03:17:47Z","generation":1,"labels":{"app":"test"},"name":"test","namespace":"default","resourceVersion":"84187","uid":"4fc9746e-47be-4ae6-9c47-2869ae0829e0"},"spec":{"progressDeadlineSeconds":600,"replicas":10,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"test"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"test"}},"spec":{"containers":[{"image":"httpd","imagePullPolicy":"Always","name":"httpd","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":10,"conditions":[{"lastTransitionTime":"2025-03-19T03:17:50Z","lastUpdateTime":"2025-03-19T03:17:50Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-03-19T03:17:47Z","lastUpdateTime":"2025-03-19T03:17:50Z","message":"ReplicaSet \"test-54bf49cb6c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":10,"replicas":10,"updatedReplicas":10}}
  creationTimestamp: "2025-03-19T03:17:47Z"
  generation: 2
  labels:
    app: test
  name: test
  namespace: default
  resourceVersion: "84666"
  uid: 4fc9746e-47be-4ae6-9c47-2869ae0829e0
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
        - image: httpd:alpine3.18
          imagePullPolicy: Always
          name: httpd
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2025-03-19T03:17:50Z"
    lastUpdateTime: "2025-03-19T03:17:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-19T03:17:47Z"
    lastUpdateTime: "2025-03-19T03:17:50Z"
    message: ReplicaSet "test-54bf49cb6c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
