apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage  # This was missing or empty in your file
  labels:
    name: nginx-storage
  namespace: mealie    # Adding this since your error shows namespace "mealie"
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  - image: busybox 
    name: busybox
    command: ["/bin/sh", "-c"]
    args: ["sleep 1000"]
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
  - name: scratch-volume
    emptyDir:
      sizeLimit: 500Mi
